sudo: false
language: node_js
node_js:
  - 9
  - node
install:
  - ./tests/fixtures/fetch.sh
  - npm install
after_script:
  - npm run cov
  - npm run covhtml
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
